name: transpiler-malt-expansion
description: ''
version: 0.0.1
author: hari@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: transpilermaltexpansion
  parentArtefactID: hariprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2024-03-07 03:54:12'
pipelines:
  pipelines/altexp_gpi_rank_ratio:
    name: altexp_gpi_rank_ratio
    description: null
    author: hari@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-03-07 03:54:12'
    datasets:
      inputs:
      - datasets/Drug_Data_Set_Drug_Data_Set_DTL
      outputs:
      - datasets/GPI_RANK_RATIO_Load
    subgraphs: []
    dependencies: {}
  pipelines/altexp_file_load_cntl_update:
    name: altexp_file_load_cntl_update
    description: null
    author: hari@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-03-07 03:54:13'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/altexp_file_load_cntl_load:
    name: altexp_file_load_cntl_load
    description: null
    author: hari@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-03-07 04:26:12'
    datasets:
      inputs:
      - datasets/Unload_Job_Details
      outputs:
      - datasets/Load_data_to_File_Load_Cntl_table
    subgraphs: []
    dependencies: {}
datasets:
  datasets/GPI_RANK_RATIO_Load:
    name: GPI_RANK_RATIO_Load
    description: 'Dataset for Imported Pipeline:altexp_gpi_rank_ratio componentName:
      GPI_RANK_RATIO_Load'
    author: hari@prophecy.io
    createdAt: '2024-03-07 03:54:12'
    mode: batch
    physicalDatasets:
      db_2:
        fabricId: 4113
        datasetType: Warehouse
        description: ''
        author: hari@prophecy.io
        createdAt: '2024-03-07 03:54:12'
  datasets/Drug_Data_Set_Drug_Data_Set_DTL:
    name: Drug_Data_Set_Drug_Data_Set_DTL
    description: 'Dataset for Imported Pipeline:altexp_gpi_rank_ratio componentName:
      Drug_Data_Set_Drug_Data_Set_DTL'
    author: hari@prophecy.io
    createdAt: '2024-03-07 03:54:12'
    mode: batch
    physicalDatasets:
      db_2:
        fabricId: 4113
        datasetType: Warehouse
        description: ''
        author: hari@prophecy.io
        createdAt: '2024-03-07 03:54:12'
  datasets/Unload_Job_Details:
    name: Unload_Job_Details
    description: 'Dataset for Imported Pipeline:altexp_file_load_cntl_load componentName:
      Unload_Job_Details'
    author: hari@prophecy.io
    createdAt: '2024-03-07 03:54:13'
    mode: batch
    physicalDatasets:
      db_2:
        fabricId: 4113
        datasetType: Warehouse
        description: ''
        author: hari@prophecy.io
        createdAt: '2024-03-07 03:54:13'
  datasets/Load_data_to_File_Load_Cntl_table:
    name: Load_data_to_File_Load_Cntl_table
    description: 'Dataset for Imported Pipeline:altexp_file_load_cntl_load componentName:
      Load_data_to_File_Load_Cntl_table'
    author: hari@prophecy.io
    createdAt: '2024-03-07 04:26:12'
    mode: batch
    physicalDatasets:
      db_2:
        fabricId: 4113
        datasetType: Warehouse
        description: ''
        author: hari@prophecy.io
        createdAt: '2024-03-07 04:26:12'
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.0.4
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-07 03:54:12'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12651':
    projectUID: 12651
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12651.git&subPath=
    version: 0.1.2
    isDefault: true
    author: null
    createdAt: '2024-03-07 03:51:52'
  '12652':
    projectUID: 12652
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12652.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-03-07 03:51:52'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
